export const HOME_SET_BANNERS = 'HOME_SET_BANNERS'
export const HOME_SET_HOTS = 'HOME_SET_HOTS'
export const HOME_SET_DOMAIN_LIST = 'HOME_SET_DOMAIN_LIST'
export const HOME_SET_CURRENT_PAGE = 'HOME_SET_CURRENT_PAGE'
